version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - run: 
         
          name: ant
          context: PersonalBox
          command: ant -lib lib/ Build
          
          
          
