version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      
      - run: 
          context: PersonalBox
          name: ant
          command: ant -lib lib/ Build

          
          
          
